### ISSUE TITLE
Add support for description field

### ISSUE THREAD

**Issue by jhanzo** [justinsinger/fastlane_plugins#1]
Project : `fastlane-plugin-github_job_status`

First, nice wrapper for Fastlane and Github Status integration ;)

Then, I think it could be interesting to have another arg in your lane for supporting Github status `description` as described on [Github Status API](https://developer.github.com/v3/repos/statuses/), doesn't it ?

**Comment by justinsinger** [comment]
Version 0.2.0 is now released and supports this feature
